### ISSUE TITLE
Create filter chain

### ISSUE THREAD

**Issue by core23** [core23/twig-extensions#3]
Create some kind of filter chain, so you have to add one filter and execute some filters at once.

Exectute the default filter chain
```yaml
{{ text|filterChain }}
```

Execute a custom filter chain:
```yaml
{{ text|filterChain('test') }}
```

If you use symfony, you could use a config to define the executed filters:

```yaml
core23_twig: 
    chain:
        default:
            - lower
            - capitalize
            - reverse
```
